<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            'Accurist',
            'Accutime',
            'Adidas',
            'All saints',
            'All we are',
            'Ambush',
            'Anne Klein',
            'Armani',
            'Aston Martin',
            'Audemars Piguet',
            'August Berg',
            'Avi-8',
            

            'Balenciaga',
            'Bauhaus',
            'Baume and Mercier',
            'Ben Sherman',
            'Bench',
            'Bering',
            'Braun',
            'Buddha To Buddha',
            'Bulova',

            'Calvin Klein',
            'Casio',
            'Cernucci',
            'Cerruti1881',
            'Certina',
            'Character',
            'Chiara Ferragni',
            'Chopard',
            'Citizen',
            'Cluse',
            'Coach',
            'Columbia',
            'Common Lines',
            'Continental',

            'Daewoo Electricals',
            'Daniel Wellington',
            'Davosa',
            'Depth Charge',
            'Diesel',
            'Disney',
            'Disney Dumbo',
            'Disney Encanto',
            'Disney Princess',
            'Dkny',
            'Dlouise',

            'Elliot brown',
            'Emilechouriet',
            'Everswiss',
            'Exaequo',

            'Fabric',
            'Festina',
            'Fitbit',
            'Flikflak',
            'Fortis',
            'Fossil',
            'French Connection',
            'Furla',

            'G shock',
            'Gant',
            'Garmin',
            'Gc',
            'Gift',
            'Gucci',
            'Guess',

            'Hamilton',
            'Harry lime',
            'Hatton labs',
            'Hello Kitty',
            'Henry london',
            'Heron preston',
            'Hirsch',
            'Huawei',
            'Hublot',
            'Hugoboss',
            'Hype',
            

            'Ingersoll',
            'Ingersoll 1892',
            'Ironannie',
            'Isabel marant',

            'Jasper Conran London',
            'Jdmmilitary',
            'Junghans',

            'Karl Lagerfeld',
            'Karrimor',
            'Kate Spade New York',
            'Kenneth cole',

            'Lacoste',
            'Levis',
            'Linea',
            'Liujo',
            'Locksley london',
            'LOL Surprise',
            'Lorus',
            'Lotus',
            'Louis Erard',
            'Luminox',

            'Magdabutrym',
            'Marc Jacobs',
            'Marchesa',
            'Maria black',
            'Marine serre',
            'Maserati',
            'Mason Knight Yager',
            'Maurice lacroix',
            'Michael Kors',
            'Minecraft',
            'Minnie mouse',
            'Miso',
            'Missoni',
            'Mondaine',
            'Montblanc',
            'Morellato',
            'Moschino',
            'Muhleglashutte',

            'Nautica',
            'Nicholas Deakins',
            'Nightmare Before Christmas',
            'Nike',
            'Nintendo',
            'Nixon',

            'Off White',
            'Official',
            'Olivia Burton',
            'Orient',
            'Oris',

            'PDPAOLA',
            'Philipp Plein',
            'Pokemon',
            'Police',
            'Porsche Design',
            'Prive Revaux',
            'Puma',

            'Rabanne',
            'Radley',
            'Rado',
            'Rag and Bone',
            'Ralph Lauren',
            'Raymond Weil',
            'Reflex',
            'Reflexactive',
            'Roamer',
            'Rolex',
            'Rotary',

            'Salvatore Ferragamo',
            'Seiko',
            'Seiko Clocks',
            'Sekonda',
            'Serge Denimes',
            'Sinn',
            'Skagen',
            'Sonic',
            'Speedometer',
            'Spinnaker',
            'Spirit',
            'Sports Direct',
            'Starwars',
            'Sternglas',
            'Storm',
            'Swarovski',
            'Swatch',
            'Swiss military',

            'Tateossian',
            'Ted Baker',
            'Thomas Sabo',
            'Thor',
            'Tianguis Jackson',
            'Tiffany',
            'Tikkers',
            'Timex',
            'Tissot',
            'Tommy Hilfiger',
            'Tudor',
            'Tw Steel',
            'TWOJEYS',

            'U-Boat',
            'Unique and co',

            'Versace',
            'Victorinox',
            'Victorinox swiss army',
            'Visconti',
            'Vivienne Westwood',

            'Wenger',
            'Winnie The Pooh',
            'Wolf',

            'Zeppelin',
        ];

        foreach ($brands as $name) {
            Brand::firstOrCreate(['name' => $name]);
        }
    }
}
