<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Watch;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Supplier;

class WatchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $rows = [
            [
                "Brand" => "rolex",
                "Supplier" => "rolex",
                "Category" => "Luxury",
                "Name" => "Submariner Date",
                "Price" => 12200,
                "Size" => "41mm",
                "Description" => "The Rolex Submariner Date combines a bold black dial with a unidirectional rotating bezel for precise dive timing. Crafted from Oystersteel with a solid-link bracelet, it’s both rugged and refined. Its reliable automatic movement and timeless design make it a cornerstone of modern luxury watchmaking.",
                "Image" => 1,
            ],
            [
                "Brand" => "Omega",
                "Supplier" => "Omega",
                "Category" => "Luxury",
                "Name" => "Seamaster Diver 300M",
                "Price" => 6100,
                "Size" => "42mm",
                "Description" => "The Omega Seamaster Diver 300M features a wave-pattern blue dial with skeleton hands and bold lume for exceptional legibility. Its helium escape valve and ceramic bezel highlight its professional dive credentials. Equally at home underwater or with a suit, it balances sportiness and elegance with ease.",
                "Image" => 2,
            ],
            [
                "Brand" => "Patek Philippe",
                "Supplier" => "Patek Philippe",
                "Category" => "Luxury",
                "Name" => "Calatrava 5227",
                "Price" => 39500,
                "Size" => "39mm",
                "Description" => "The Patek Philippe Calatrava 5227 showcases a clean ivory lacquered dial framed by a polished round case. Subtle dauphine hands and applied indices give it a quiet, classical charm. Paired with a leather strap, it’s a quintessential dress watch for those who favor understated sophistication.",
                "Image" => 3,
            ],
            [
                "Brand" => "Audemars Piguet",
                "Supplier" => "Audemars Piguet",
                "Category" => "Luxury",
                "Name" => "Royal Oak Selfwinding",
                "Price" => 28500,
                "Size" => "41mm",
                "Description" => "The Audemars Piguet Royal Oak Selfwinding stands out with its iconic octagonal bezel and tapisserie-pattern dial. Integrated bracelet links flow seamlessly from the case for a sculpted, architectural look. Its mix of brushed and polished surfaces makes it instantly recognizable on the wrist.",
                "Image" => 4,
            ],
            [
                "Brand" => "Vacheron Constantin",
                "Supplier" => "Vacheron Constantin",
                "Category" => "Luxury",
                "Name" => "Overseas Automatic",
                "Price" => 26000,
                "Size" => "41mm",
                "Description" => "The Vacheron Constantin Overseas Automatic pairs a sunburst blue dial with a bold, angular bezel. Interchangeable straps and bracelet offer versatile styling from casual to formal. With fine finishing throughout, it’s a refined travel companion for those with a taste for haute horlogerie.",
                "Image" => 5,
            ],
            [
                "Brand" => "Jaeger‑LeCoultre",
                "Supplier" => "Jaeger‑LeCoultre",
                "Category" => "Luxury",
                "Name" => "Reverso Classic Large",
                "Price" => 9800,
                "Size" => "45mm x 27mm",
                "Description" => "The Jaeger‑LeCoultre Reverso Classic Large features a rectangular swiveling case that nods to its polo origins. A silvered dial with Art Deco numerals delivers vintage charm and balance. Flip the case over and you reveal a sleek steel back, ideal for engraving or personalization.",
                "Image" => 6,
            ],
            [
                "Brand" => "Cartier",
                "Supplier" => "Cartier",
                "Category" => "Luxury",
                "Name" => "Santos de Cartier Large",
                "Price" => 8700,
                "Size" => "39.8mm",
                "Description" => "The Santos de Cartier Large presents a square case with exposed screws that feel both industrial and elegant. Its crisp Roman numerals and blue sword hands give it a distinctly Parisian flair. Comfortable on the wrist, it transitions easily from office wear to evening attire.",
                "Image" => 7,
            ],
            [
                "Brand" => "IWC",
                "Supplier" => "IWC",
                "Category" => "Luxury",
                "Name" => "Portugieser Automatic",
                "Price" => 13500,
                "Size" => "42.3mm",
                "Description" => "The IWC Portugieser Automatic is defined by a spacious dial with small seconds and a power‑reserve display. Slim feuille hands and Arabic numerals create a refined, nautical-inspired aesthetic. Its transparent caseback reveals a beautifully finished automatic movement.",
                "Image" => 8,
            ],
            [
                "Brand" => "Breguet",
                "Supplier" => "Breguet",
                "Category" => "Luxury",
                "Name" => "Classique 5177",
                "Price" => 23000,
                "Size" => "38mm",
                "Description" => "The Breguet Classique 5177 showcases a hand‑guilloché dial accented by blued Breguet hands and Roman numerals. A thin, polished bezel and coin‑edge caseband highlight traditional watchmaking details. It’s a graceful choice for those who appreciate old‑world craftsmanship.",
                "Image" => 9,
            ],
            [
                "Brand" => "Blancpain",
                "Supplier" => "Blancpain",
                "Category" => "Luxury",
                "Name" => "Fifty Fathoms Automatique",
                "Price" => 16000,
                "Size" => "45mm",
                "Description" => "The Blancpain Fifty Fathoms Automatique combines a deep black dial with oversized luminous markers for superior underwater visibility. Its domed sapphire bezel and robust case emphasize its tool‑watch roots. While designed for professional diving, its refined finishing makes it equally compelling on land.",
                "Image" => 10,
            ],
            [
                "Brand" => "Apple",
                "Supplier" => "Apple",
                "Category" => "Smart",
                "Name" => "Apple Watch Series 9",
                "Price" => 399,
                "Size" => "45mm",
                "Description" => "The Apple Watch Series 9 features an always‑on Retina display that keeps key information visible at a glance. Advanced health sensors track heart rate, blood oxygen, and workouts throughout your day. Seamless integration with the Apple ecosystem makes it a powerful extension of your iPhone.",
                "Image" => 11,
            ],
            [
                "Brand" => "Samsung",
                "Supplier" => "Samsung",
                "Category" => "Smart",
                "Name" => "Galaxy Watch6",
                "Price" => 349,
                "Size" => "44mm",
                "Description" => "The Samsung Galaxy Watch6 pairs a bright circular display with a slim, comfortable profile. It offers detailed sleep tracking, fitness metrics, and body composition insights from the wrist. With robust app support and LTE options, it’s built for life on the go.",
                "Image" => 12,
            ],
            [
                "Brand" => "Garmin",
                "Supplier" => "Garmin",
                "Category" => "Smart",
                "Name" => "Venu Sq 2",
                "Price" => 249,
                "Size" => "40mm",
                "Description" => "The Garmin Venu Sq 2 sports a crisp AMOLED display surrounded by a lightweight case. Built‑in GPS, heart‑rate monitoring, and a wide range of sport modes make it ideal for active users. Long battery life keeps it running through busy schedules and extended workouts.",
                "Image" => 13,
            ],
            [
                "Brand" => "Fitbit",
                "Supplier" => "Fitbit",
                "Category" => "Smart",
                "Name" => "Versa 4",
                "Price" => 229,
                "Size" => "40mm",
                "Description" => "The Fitbit Versa 4 offers daily readiness scores, guided workouts, and stress‑management tools in a slim design. Its simple interface and comfortable strap make it easy to wear all day and night. Detailed health metrics sync seamlessly with the Fitbit app to show your long‑term trends.",
                "Image" => 14,
            ],
            [
                "Brand" => "Huawei",
                "Supplier" => "Huawei",
                "Category" => "Smart",
                "Name" => "Watch GT 4",
                "Price" => 279,
                "Size" => "46mm",
                "Description" => "The Huawei Watch GT 4 combines a classic round case with modern smartwatch capabilities. It provides multi‑band GPS, advanced fitness tracking, and strong battery performance that can last for days. Customizable watch faces let you shift from sporty to formal in seconds.",
                "Image" => 15,
            ],
            [
                "Brand" => "Amazfit",
                "Supplier" => "Amazfit",
                "Category" => "Smart",
                "Name" => "Amazfit GTR 4",
                "Price" => 199,
                "Size" => "46mm",
                "Description" => "The Amazfit GTR 4 features a sharp high‑resolution display framed by a robust metal bezel. Over a hundred sport modes, dual‑band GPS, and heart‑rate tracking support serious training. Despite its capabilities, it remains comfortable and stylish enough for all‑day wear.",
                "Image" => 16,
            ],
            [
                "Brand" => "Fossil",
                "Supplier" => "Fossil",
                "Category" => "Smart",
                "Name" => "Gen 6",
                "Price" => 299,
                "Size" => "44mm",
                "Description" => "The Fossil Gen 6 blends classic watch styling with the flexibility of Wear OS by Google. Traditional lugs and pushers are paired with a vibrant touchscreen for notifications and apps. Fast charging and customizable dials keep it practical as well as fashionable.",
                "Image" => 17,
            ],
            [
                "Brand" => "Mobvoi",
                "Supplier" => "Mobvoi",
                "Category" => "Smart",
                "Name" => "TicWatch Pro 5",
                "Price" => 349,
                "Size" => "45mm",
                "Description" => "The TicWatch Pro 5 uses a unique dual‑display system to maximize both visibility and battery life. Rugged construction, GPS, and health tracking make it suitable for outdoor adventures. Its Wear OS platform provides access to Google services, apps, and voice assistance.",
                "Image" => 18,
            ],
            [
                "Brand" => "Withings",
                "Supplier" => "Withings",
                "Category" => "Smart",
                "Name" => "ScanWatch",
                "Price" => 299,
                "Size" => "42mm",
                "Description" => "The Withings ScanWatch combines an analog dial with discreet smart features and a small digital window. It tracks heart health, sleep, and activity with medical‑grade inspired sensors. Its hybrid design keeps it looking like a classic watch while quietly logging your daily metrics.",
                "Image" => 19,
            ],
            [
                "Brand" => "Garmin",
                "Supplier" => "Garmin",
                "Category" => "Smart",
                "Name" => "Fenix 7 Pro",
                "Price" => 899,
                "Size" => "47mm",
                "Description" => "The Garmin Fenix 7 Pro is built for explorers, with robust construction and multi‑band satellite positioning. Solar charging options, advanced training tools, and topographic maps support demanding adventures. Despite its toughness, it remains surprisingly wearable for everyday use.",
                "Image" => 20,
            ],
            [
                "Brand" => "TAG Heuer",
                "Supplier" => "TAG Heuer",
                "Category" => "Sports",
                "Name" => "Formula 1 Chronograph",
                "Price" => 2250,
                "Size" => "43mm",
                "Description" => "The TAG Heuer Formula 1 Chronograph features a bold bezel and high‑contrast dial inspired by motor racing. Large pushers and clear subdials make timing laps quick and intuitive. Its sporty bracelet and robust case are built to handle fast‑paced lifestyles.",
                "Image" => 21,
            ],
            [
                "Brand" => "Seiko",
                "Supplier" => "Seiko",
                "Category" => "Sports",
                "Name" => "Prospex Turtle Diver",
                "Price" => 650,
                "Size" => "45mm",
                "Description" => "The Seiko Prospex Turtle Diver offers a cushion‑shaped case and large luminous markers for easy legibility. Its reliable automatic movement and 200‑meter water resistance make it a trusted dive companion. The watch’s informal charm pairs equally well with wetsuits and weekend wear.",
                "Image" => 22,
            ],
            [
                "Brand" => "Citizen",
                "Supplier" => "Citizen",
                "Category" => "Sports",
                "Name" => "Promaster Diver Eco‑Drive",
                "Price" => 425,
                "Size" => "44mm",
                "Description" => "The Citizen Promaster Diver Eco‑Drive harnesses light to power its movement, eliminating the need for battery changes. A chunky bezel and oversized hands ensure quick readability under water. Its rugged construction and ISO‑certified dive rating underscore its purpose‑built nature.",
                "Image" => 23,
            ],
            [
                "Brand" => "Tissot",
                "Supplier" => "Tissot",
                "Category" => "Sports",
                "Name" => "T‑Sports PRC 200",
                "Price" => 575,
                "Size" => "42mm",
                "Description" => "The Tissot PRC 200 chronograph blends a clean dial with sporty subdials and a tachymeter scale. Screw‑down crown and pushers contribute to its solid 200‑meter water resistance. It’s a versatile option for those who want a timing tool that still fits under a cuff.",
                "Image" => 24,
            ],
            [
                "Brand" => "Casio",
                "Supplier" => "Casio",
                "Category" => "Sports",
                "Name" => "G‑Shock GA‑2100",
                "Price" => 150,
                "Size" => "45mm",
                "Description" => "The Casio G‑Shock GA‑2100, often nicknamed the “CasiOak,” features an angular octagonal case that feels modern and rugged. Shock resistance and strong water protection make it a true beater watch. Its lightweight resin construction keeps it comfortable for all‑day wear.",
                "Image" => 25,
            ],
            [
                "Brand" => "Hamilton",
                "Supplier" => "Hamilton",
                "Category" => "Sports",
                "Name" => "Khaki Navy Scuba",
                "Price" => 845,
                "Size" => "40mm",
                "Description" => "The Hamilton Khaki Navy Scuba pairs a colorful bezel with a straightforward, legible dial. Sportsy indices and a robust bracelet give it a summery, beach‑ready character. With reliable automatic movement and solid water resistance, it’s ideal for weekend adventures.",
                "Image" => 26,
            ],
            [
                "Brand" => "Longines",
                "Supplier" => "Longines",
                "Category" => "Sports",
                "Name" => "HydroConquest",
                "Price" => 1850,
                "Size" => "41mm",
                "Description" => "The Longines HydroConquest sports a ceramic bezel and applied markers for a sharp, modern look. Its combination of robust case construction and refined detailing makes it a strong all‑rounder. On the wrist, it reads as both an everyday diver and a polished sports watch.",
                "Image" => 27,
            ],
            [
                "Brand" => "Oris",
                "Supplier" => "Oris",
                "Category" => "Sports",
                "Name" => "Aquis Date",
                "Price" => 2300,
                "Size" => "43.5mm",
                "Description" => "The Oris Aquis Date features broad hands, applied indices, and a glossy ceramic bezel for clear underwater reading. Integrated‑style lugs give it a contemporary, muscular stance. With a reliable automatic movement and quick‑adjust bracelet options, it’s well suited to active lifestyles.",
                "Image" => 28,
            ],
            [
                "Brand" => "Breitling",
                "Supplier" => "Breitling",
                "Category" => "Sports",
                "Name" => "Superocean Automatic",
                "Price" => 5200,
                "Size" => "42mm",
                "Description" => "The Breitling Superocean Automatic delivers bold color accents and a chunky bezel that celebrates its dive heritage. Oversized numerals and hands glow brightly for low‑light visibility. Its solid case and bracelet construction are built to endure years of sea‑going adventures.",
                "Image" => 29,
            ],
            [
                "Brand" => "Sinn",
                "Supplier" => "Sinn",
                "Category" => "Sports",
                "Name" => "U1 Diver",
                "Price" => 2900,
                "Size" => "44mm",
                "Description" => "The Sinn U1 Diver is forged from submarine steel, offering exceptional hardness and corrosion resistance. Its unique blocky hands and indices give it a distinctive, functional look. Designed for demanding environments, it remains surprisingly comfortable for everyday wear.",
                "Image" => 30,
            ],
            [
                "Brand" => "Seiko",
                "Supplier" => "Seiko",
                "Category" => "Casual",
                "Name" => "Seiko 5 Sportss",
                "Price" => 330,
                "Size" => "40mm",
                "Description" => "The Seiko 5 Sportss offers a laid‑back design with a day‑date display and sporty bezel. Its automatic movement and see‑through caseback add enthusiast appeal at an accessible price point. Paired with a bracelet or nylon strap, it’s an easy everyday companion.",
                "Image" => 31,
            ],
            [
                "Brand" => "Timex",
                "Supplier" => "Timex",
                "Category" => "Casual",
                "Name" => "Weekender",
                "Price" => 75,
                "Size" => "38mm",
                "Description" => "The Timex Weekender keeps things simple with a clean dial and bright Indiglo backlight. Its quick‑release straps make it easy to switch between canvas, leather, or nylon. Lightweight and affordable, it’s a no‑fuss watch you can grab and go.",
                "Image" => 32,
            ],
            [
                "Brand" => "Tissot",
                "Supplier" => "Tissot",
                "Category" => "Casual",
                "Name" => "Gentleman Powermatic 80",
                "Price" => 875,
                "Size" => "40mm",
                "Description" => "The Tissot Gentleman Powermatic 80 features a balanced three‑hand dial with a discreet date window. Subtle applied indices and polished details give it a smart‑casual character. Its long‑running automatic movement means you can wear it all week without winding.",
                "Image" => 33,
            ],
            [
                "Brand" => "Orient",
                "Supplier" => "Orient",
                "Category" => "Casual",
                "Name" => "Bambino Version IV",
                "Price" => 260,
                "Size" => "40.5mm",
                "Description" => "The Orient Bambino Version IV showcases a domed crystal and minimalist dial for a vintage‑inspired look. Slim hands and markers keep the design relaxed yet refined. It’s equally at home with rolled‑up sleeves or a light blazer.",
                "Image" => 34,
            ],
            [
                "Brand" => "Citizen",
                "Supplier" => "Citizen",
                "Category" => "Casual",
                "Name" => "Chandler Eco‑Drive",
                "Price" => 225,
                "Size" => "42mm",
                "Description" => "The Citizen Chandler Eco‑Drive pairs a field‑style dial with easy‑to‑read numerals and a canvas strap. Solar‑powered technology keeps it running from ambient light alone. Its versatile design works well in both office and weekend settings.",
                "Image" => 35,
            ],
            [
                "Brand" => "Swatch",
                "Supplier" => "Swatch",
                "Category" => "Casual",
                "Name" => "Big Bold",
                "Price" => 160,
                "Size" => "47mm",
                "Description" => "The Swatch Big Bold lives up to its name with a large, playful case and graphic dial. Lightweight materials keep it comfortable despite the size. It’s a fun option for injecting color and personality into everyday outfits.",
                "Image" => 36,
            ],
            [
                "Brand" => "MVMT",
                "Supplier" => "MVMT",
                "Category" => "Casual",
                "Name" => "Chrono Gunmetal Sandstone",
                "Price" => 195,
                "Size" => "45mm",
                "Description" => "The MVMT Chrono Gunmetal Sandstone offers a minimalist chronograph layout with contrasting subdials. A muted color palette and clean case lines give it a contemporary, urban feel. It’s designed for those who prefer a sleek, fashion‑forward look.",
                "Image" => 37,
            ],
            [
                "Brand" => "Daniel Wellington",
                "Supplier" => "Daniel Wellington",
                "Category" => "Casual",
                "Name" => "Classic St Mawes",
                "Price" => 229,
                "Size" => "40mm",
                "Description" => "The Daniel Wellington Classic St Mawes showcases a slim case with a simple, uncluttered dial. Its brown leather strap and polished bezel create an easygoing, preppy aesthetic. Lightweight and versatile, it pairs effortlessly with casual or smart‑casual attire.",
                "Image" => 38,
            ],
            [
                "Brand" => "Bulova",
                "Supplier" => "Bulova",
                "Category" => "Casual",
                "Name" => "Classic Surveyor",
                "Price" => 350,
                "Size" => "41mm",
                "Description" => "The Bulova Classic Surveyor features a sunray dial with applied indices and a framed date window. Modest case dimensions and gentle curves keep it comfortable for daily wear. It offers a polished look without feeling overly formal.",
                "Image" => 39,
            ],
            [
                "Brand" => "Casio",
                "Supplier" => "Casio",
                "Category" => "Casual",
                "Name" => "Vintage A168",
                "Price" => 45,
                "Size" => "36mm",
                "Description" => "The Casio Vintage A168 brings digital nostalgia with its compact square case and retro display. A built‑in backlight, alarm, and stopwatch add practical everyday functions. Its chrome‑style finish and bracelet make it a fun, low‑key statement piece.",
                "Image" => 40,
            ],
            [
                "Brand" => "Rolex",
                "Supplier" => "Rolex",
                "Category" => "Classic",
                "Name" => "Datejust 36",
                "Price" => 9900,
                "Size" => "36mm",
                "Description" => "The Rolex Datejust 36 pairs a fluted bezel with a timeless Oyster case silhouette. Its clean dial, date window, and Cyclops lens create a look that has remained relevant for decades. Versatile and refined, it’s equally suited to formal events and daily wear.",
                "Image" => 41,
            ],
            [
                "Brand" => "Omega",
                "Supplier" => "Omega",
                "Category" => "Classic",
                "Name" => "De Ville Prestige",
                "Price" => 5600,
                "Size" => "39.5mm",
                "Description" => "The Omega De Ville Prestige offers a graceful, rounded case and a subtle sunburst dial. Slender hands and Roman numerals give it an old‑world charm. On a leather strap, it embodies traditional dress‑watch elegance.",
                "Image" => 42,
            ],
            [
                "Brand" => "Longines",
                "Supplier" => "Longines",
                "Category" => "Classic",
                "Name" => "Master Collection Moonphase",
                "Price" => 3250,
                "Size" => "40mm",
                "Description" => "The Longines Master Collection Moonphase features a textured dial with a romantic moonphase display at six o’clock. Blued hands and applied indices add a touch of sophistication. It’s a classic choice for those who enjoy a hint of complication in a refined package.",
                "Image" => 43,
            ],
            [
                "Brand" => "Jaeger‑LeCoultre",
                "Supplier" => "Jaeger‑LeCoultre",
                "Category" => "Classic",
                "Name" => "Master Control Date",
                "Price" => 11800,
                "Size" => "40mm",
                "Description" => "The Jaeger‑LeCoultre Master Control Date presents a slim round case with balanced dial proportions. Dauphine hands and a discreet date window keep the design clean and legible. Its restrained style makes it an enduring staple in any classic collection.",
                "Image" => 44,
            ],
            [
                "Brand" => "Grand Seiko",
                "Supplier" => "Grand Seiko",
                "Category" => "Classic",
                "Name" => "Heritage SBGH301",
                "Price" => 6400,
                "Size" => "40mm",
                "Description" => "The Grand Seiko Heritage SBGH301 showcases razor‑sharp hands and indices finished to a mirror‑like sheen. A subtle sunburst dial and precise automatic movement emphasize craftsmanship over flash. It’s a watch that rewards close inspection and quiet appreciation.",
                "Image" => 45,
            ],
            [
                "Brand" => "Nomos",
                "Supplier" => "Nomos",
                "Category" => "Classic",
                "Name" => "Tangente 38",
                "Price" => 2450,
                "Size" => "38mm",
                "Description" => "The Nomos Tangente 38 interprets Bauhaus design with a slim case, long lugs, and crisp typography. Its small‑seconds subdial and thin hands keep the look airy and precise. Under the sapphire back, an in‑house movement reflects meticulous German engineering.",
                "Image" => 46,
            ],
            [
                "Brand" => "Frederique Constant",
                "Supplier" => "Frederique Constant",
                "Category" => "Classic",
                "Name" => "Classics Index Automatic",
                "Price" => 1350,
                "Size" => "40mm",
                "Description" => "The Frederique Constant Classics Index Automatic features a clean dial with applied markers and a framed date display. Its polished case and leather strap strike a traditional dress‑watch tone. It offers a refined, timeless look at an accessible luxury price.",
                "Image" => 47,
            ],
            [
                "Brand" => "Hamilton",
                "Supplier" => "Hamilton",
                "Category" => "Classic",
                "Name" => "Intra‑Matic Auto",
                "Price" => 1095,
                "Size" => "38mm",
                "Description" => "The Hamilton Intra‑Matic Auto channels mid‑century design with its domed crystal and minimalist dial. Thin hands and a subtle date window preserve its vintage‑inspired charm. Compact dimensions make it an easy, comfortable daily dress piece.",
                "Image" => 48,
            ],
            [
                "Brand" => "Cartier",
                "Supplier" => "Cartier",
                "Category" => "Classic",
                "Name" => "Tank Must",
                "Price" => 3950,
                "Size" => "33.7mm x 25.5mm",
                "Description" => "The Cartier Tank Must carries the unmistakable rectangular case and cabochon crown of the Tank line. Roman numerals and chemin‑de‑fer minute track give the dial a refined, Parisian character. Slim and elegant, it slips effortlessly under a cuff.",
                "Image" => 49,
            ],
            [
                "Brand" => "Mido",
                "Supplier" => "Mido",
                "Category" => "Classic",
                "Name" => "Baroncelli Heritage",
                "Price" => 1100,
                "Size" => "39mm",
                "Description" => "The Mido Baroncelli Heritage showcases a slim profile with a finely detailed dial and leaf‑style hands. A transparent caseback reveals its automatic movement, adding mechanical charm. It’s an understated classic suited to both business and evening wear.",
                "Image" => 50,
            ],
        ];

        foreach ($rows as $row) {

            // CREATE BRAND
            $brand = Brand::firstOrCreate([
                'name' => $row['Brand'] ?? 'Unknown Brand'
            ]);

            // CREATE CATEGORY
            $category = Category::firstOrCreate([
                'name' => strtolower($row['Category'] ?? 'classic')
            ]);

            // CREATE CATEGORY
            $supplier = Supplier::firstOrCreate([
                'name' => strtolower($row['Supplier'] ?? 'classic'),
                'contact' => "0782302893009"
            ]);

            // Fallbacks for missing values
            $name = $row['Name'] ?? "Watch Model " . rand(1000, 9999);
            $price = $row['Price'] ?? rand(100, 5000);
            $size = isset($row['Size'])
                ? (int) filter_var($row['Size'], FILTER_SANITIZE_NUMBER_INT)
                : rand(36, 45);
            $description = $row['Description'] ?? "No description available.";
            $image = $row['Image'] ?? rand(1, 50);

            Watch::create([
                'brand_id'    => $brand->id,
                'supplier_id' => $supplier->id,
                'category_id' => $category->id,
                'name'        => $name,
                'price'       => $price,
                'description' => $description,
                'image_path'  => "watches/{$image}.png",
            ]);
        }
    }
}
